Repository geopython/diving-into-pygeoapi, pull requests merged in 2023-06, with the labels that each got.

#95 minor editorial changes Setup chapter
  workshop/content/docs/setup.md
Labels: documentation

#96 #88 #91 add CRS support, plus config file cleanup
  workshop/content/docs/advanced/crs.md
  workshop/content/docs/advanced/index.md
  workshop/content/docs/publishing/ogcapi-features.md
  workshop/content/mkdocs.yml
  workshop/exercises/pygeoapi.config.yml
Labels: enhancement

#97 add section on OGC API - Maps (#90)
  workshop/content/docs/publishing/index.md
  workshop/content/docs/publishing/ogcapi-coverages.md
  workshop/content/docs/publishing/ogcapi-features.md
  workshop/content/docs/publishing/ogcapi-maps.md
  workshop/exercises/pygeoapi.config.yml
Labels: documentation, enhancement

#100 #98 OWSLib in Docker Python Container - setup doc and refs
  workshop/content/docs/publishing/ogcapi-coverages.md
  workshop/content/docs/publishing/ogcapi-features.md
  workshop/content/docs/publishing/ogcapi-maps.md
  workshop/content/docs/publishing/ogcapi-records.md
  workshop/content/docs/setup.md
Labels: enhancement
