Repository geopython/diving-into-pygeoapi, pull requests merged in 2025-07, with the labels that each got.

#198 Updated server limits key on pygeoapi configuration
  workshop/exercises/pygeoapi.config.yml
Labels: bug

#199 - Put back QGIS client example on tiles section
  workshop/content/docs/assets/images/qgis-vtiles-hyderabad1.png
  workshop/content/docs/assets/images/qgis-vtiles-hyderabad2.png
  workshop/content/docs/assets/images/qgis-vtiles-hyderabad3.png
  workshop/content/docs/publishing/ogcapi-tiles.md
Labels: documentation

#206 Use docker compose down --remove-orphans i.s.o stop
  workshop/content/docs/publishing/first.md
Labels: documentation, enhancement

#207 More fixes pygeoapi.config.yml
  workshop/content/docs/publishing/ogcapi-features.md
  workshop/exercises/pygeoapi.config.yml
Labels: bug
